### ISSUE TITLE
Some questions about trippin.yaml

### ISSUE THREAD

**Issue by dingeins** [OData/model-first#1]
First of all great work! We all know how much work would handcrafting the TripPin model take. Not to mention the assumptions and model-first.md that you wrote.

The following questions may be already answered by the assumptions.md but it's a long doc so I'd just use this issue to find the answer without reading the assumptions first. They are:
1. Under `serviceRoot`, the two operations `getNearestAirport` and `resetDataSource` are not listed in a "associative array" format (key-value pairs). It seems inconsistent with the entity sets and singletons. I understand the intension behind to simply the specification. But is this particular simplification a good experience?
2. Same to some `optionalProperties` and `requiredProperties` specification. Representation of properties whose type is string is simplified. But it makes it look distinct from other properties. Should we pursue that?
3. Would specifying the conformance level, auth, and supported filter functions be too much for describing a RESTful service? In addition, conformance level and supported filter functions are OData concepts. Are we not trying to avoid having OData concepts in this doc?

**Comment by liqian19891011** [comment]
The Yaml format definitely more easy-to-read. Adding a few questions

1. Do we have to care the letter case? Have noticed that all the "name" in the trippin,yaml is lower case, like trip. 
2. About annotations like `searchable`, `insertable`, should these defaults to be `true` and only show them in the YAML file when it's to be `false`
3. I'm a little confused with the correct format for the required properties. I've noticed there are two formats: within a [] ; don't have a [], for example

In trippin.yaml
```
- name: location
  dynamic: true
  requiredProperties:
    - address
    - name: city
      type: city
```

and 
In trippin.yaml
```
- name: city
    requiredProperties: [countryRegion, name, region]
```

and 
```

and
In model-first.md exmple
```
- name: person
    key: [id]
    requiredProperties: [{name: id, type: int64}, firstName, lastName, {name: joinedAt, type: dateTimeOffset}]
```

**Comment by markdstafford** [comment]
@dingeins - thanks for the feedback.

> Under  serviceRoot , the two operations  getNearestAirport  and  resetDataSource  are not listed in a "associative array" format (key-value pairs). It seems inconsistent with the entity sets and singletons. I understand the intension behind to simply the specification. But is this particular simplification a good experience?

Good question. Let me ask a different question that may make your question a moot point. Do we need an `operations` section at all? Look at how we did bound functions/actions. Should "unbound" actions/functions be done the same way, but under the service root? See a1e8e6666d7b3ce6485741245cd4dfc11e8efc50 for a diff on what this might look like.

**Comment by markdstafford** [comment]
@dingeins - continued:

> Same to some  optionalProperties  and  requiredProperties  specification. Representation of properties whose type is string is simplified. But it makes it look distinct from other properties. Should we pursue that?

The simplified property format is just a simplified option. One could also use the name/type key-value pairs to clarify that it's a string. I was trying to mix the syntax a little bit intentionally to make sure that our parsing logic works. Let me know if that doesn't answer your question.

> Would specifying the conformance level, auth, and supported filter functions be too much for describing a RESTful service? In addition, conformance level and supported filter functions are OData concepts. Are we not trying to avoid having OData concepts in this doc?

This was a direct reverse-engineering of TripPin. As such it has some more advanced concepts in it, but I tried to avoid any specific OData jargon. None of these concepts are required to be specified, they're just there because the exercise was reverse-engineering. The todo-minimal.yaml is an example of a service that has the bare minimum of what would be required. (Although technically you could get even more minimalistic if you only had an unbound action, it just wouldn't be a very useful REST API.)

**Comment by dingeins** [comment]
@markdstafford 

> Do we need an operations section at all?

I think the [`a1e8e66`](https://github.com/OData/model-first/commit/a1e8e6666d7b3ce6485741245cd4dfc11e8efc50) looks great. 

> Should "unbound" actions/functions be done the same way, but under the service root?

I don't think "unbound" and "non-import" operations/functions should appear under service root. The simple reason is they just aren't under service root.

> Let me know if that doesn't answer your question.

Yes, it does.

> None of these concepts are required to be specified, they're just there because the exercise was reverse-engineering.

Generally I'd think we either go the all simplified extreme or go the nothing simplified extreme. That is to say, making something optional increase the learning amount users need to take to use this tooling. Just as the OData protocol, although over 50% the specifications are MAY/SHOULD instead of MUST, people would still think they need to learn them to use OData. So basically I'm suggesting we either make all MAY & SHOULD MUST, or we remove all MAY & SHOULD, for our tooling.
