### ISSUE TITLE
[BugBash] Function return collection should not return 204

### ISSUE THREAD

**Issue by LianwMS** [OData/model-first#128]
If a collection-valued function has no result for a given parameter value combination, the response is the format-specific representation of an empty collection. If a single-valued function with a nullable return-type has no result, the service returns 204 No Content.
If a single-valued function with a non-nullable return type has no result, the service returns 4xx. For functions that return a single entity 404 Not Found is the appropriate response code.

**Comment by lqtian** [comment]
For a single-valued function with a non-nullable return type has no result, it should be a service bug. 4XX would be returned by its parent path.

**Comment by LianwMS** [comment]
https://github.com/OData/model-first/pull/144
