### ISSUE TITLE
Type assumption

### ISSUE THREAD

**Issue by liqian19891011** [OData/model-first#3]
In the assumptions.md

> The default type for a key property is a 32-bit integer

> If not specified, a property's type is string.

Sorry I didn't quite understand why the default type for key property and non-key properties should be different. Will that be hard for users to remember ?

**Comment by markdstafford** [comment]
I don't think so based upon a survey of existing REST APIs. I'm definitely willing to reconsider if we get additional feedback that the default types should be the same.
