### ISSUE TITLE
[Optimize Design] The order of collections under serviceRoot/root in simple YAML is not same with the elements under paths in swagger format

### ISSUE THREAD

**Issue by Baoming520** [OData/model-first#34]
We define the simple YAML as:

serviceRoot:
  # Collection
  - name: Items
    type: Book
  - name: Books
    type: Book[]
  - name: OneBlog
    type: Blog 

But we get the results in  as:

"paths": {
    "/Books": {},
    "/Items": {},
    "/OneBlog": {}
}

**Comment by LianwMS** [comment]
Fix with https://github.com/OData/model-first/pull/37
