### ISSUE TITLE
The parameter's type of actions and functions has a bad format in Swagger

### ISSUE THREAD

**Issue by Baoming520** [OData/model-first#48]
Some functions and actions show the parameter's type as follows in swagger:

{
    ...
    "type": {
        "type": "integer",
        "format": "int32"
    }
    ...
}

It should be refine to:

{
    ...
    "type": "integer",
    "format": "int32"
    ...
}

**Comment by LianwMS** [comment]
https://github.com/OData/model-first/pull/50
